name: GPT Bridge

on:
  push:
    paths:
      - 'input.json'

jobs:
  handle-gpt-command:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Установить зависимости (esbuild, если нужно)
        run: |
          npm install

      - name: Чтение input.json
        id: gpt_read
        run: |
          echo "\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0430 GPT-\u043a\u043e\u043c\u0430\u043d\u0434\u044b..."
          cat input.json
          export ACTION=$(jq -r '.action' input.json)
          export CONTENT=$(jq -r '.content' input.json)
          echo "GPT Action: $ACTION"
          echo "GPT Content: $CONTENT"

      - name: Обнуление input.json
        run: |
          echo '{"action": "", "content": ""}' > input.json
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add input.json
          git commit -m "Очистка input.json после обработки"
          git push
